name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ${{ matrix.os }}

    permissions:
      contents: write
    
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 24

      - name: Install Dependencies
        run: npm install

      - name: Compile TypeScript and Assets
        run: npm run build

      - name: Build and Publish with electron-builder
        uses: samuelmeuli/action-electron-builder@v1
        with:
          use_vue_cli: false
          max_attempts: 3
          github_token: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}